const NarutoTechTemplate = require('./models/NarutoTechTemplate');

const ALL = ['ninpou', 'doton', 'fuuton', 'katon', 'raiton', 'suiton'];

const TEMPLATES = [
  // ── Ninpou Gerais (Livro Básico) ──────────────────────────────────────────
  {
    _id: 'canhao',
    name: 'Canhão',
    unlockLevel: 1,
    category: 'projectile',
    action: 'Padrão',
    range: 'Comum do poder (à distância)',
    baseDamage: '2 por nível usado do poder',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: 'Nível do efeito usado',
    description: 'Dispara um ataque em jato contra um alvo usando seu elemento. A partir do nível 2, pode ser usado sem custo de chakra, mas com metade do dano e sem acumular benefícios.',
    evolutions: 'Nv 2: Pode ser usado sem custo de chakra (metade do dano, sem benefícios).',
    availableFor: ALL,
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'criar-arma',
    name: 'Criar Arma',
    unlockLevel: 2,
    category: 'support',
    action: 'Parcial',
    range: 'Pessoal',
    baseDamage: 'Dano da arma criada (tabela de armas)',
    duration: 'Sustentada (não-sólidas) ou Permanente (sólidas)',
    target: 'O próprio usuário',
    chakraCost: '1',
    description: 'Cria armas simples ou marciais (leve, longa, mediana ou arremesso). Armas recebem vantagens/fraquezas do elemento. Permitem Bloqueio contra projéteis.',
    evolutions: 'Nv 6: Cria armas pesadas e para tamanhos acima de médio.',
    availableFor: ['ninpou', 'doton', 'suiton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'orbe',
    name: 'Orbe',
    unlockLevel: 2,
    category: 'projectile',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: 'Comum do poder',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Cria um projétil esférico de 0,5m de diâmetro e dispara contra o alvo.',
    evolutions: 'Nv 7: Custa metade do chakra, mas sem benefícios de outros efeitos/aptidões.',
    availableFor: ALL,
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'raio',
    name: 'Raio',
    unlockLevel: 2,
    category: 'projectile',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: '2 por nível usado do poder',
    duration: 'Instantânea',
    target: 'Uma ou mais criaturas',
    chakraCost: 'Padrão do poder',
    description: 'Acerta o inimigo com um raio que NÃO pode ser defendido com Bloqueio (exceto arma especial).',
    evolutions: 'Nv 5: 1 Raio para cada 2 níveis no poder (alvos a até 4m entre si). Nv 8: Ação completa, +2 dano base contra alvo único.',
    availableFor: ALL,
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'restringente',
    name: 'Restringente',
    unlockLevel: 2,
    category: 'area',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: '',
    duration: 'Contínua',
    target: 'Criaturas na área',
    chakraCost: 'Padrão do poder',
    description: 'Cria camada grudenta no chão. Criaturas ficam lentas. Vítima pode testar Escapar ou Força como ação livre para se livrar por um turno.',
    evolutions: 'Nv 6: Vítimas ficam impedidas ao invés de lentas.',
    availableFor: ['ninpou', 'doton', 'suiton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'barreira',
    name: 'Barreira',
    unlockLevel: 3,
    category: 'support',
    action: 'Movimento',
    range: 'Comum do poder',
    baseDamage: '',
    duration: 'Permanente (sólidas) ou Sustentada',
    target: 'O próprio usuário (defesa)',
    chakraCost: 'Padrão do poder',
    description: 'Conjura muro ou semicilindro (metade do tamanho comum). Dureza padrão. Teste de LM +2 precisão para defesa. Quando destruída, diferença de dano ultrapassa.',
    evolutions: 'Nv 6: Torna-se redoma (semiesfera), pode enjaular inimigos (ação padrão, CD -2). Nv 9: Dureza +2.',
    availableFor: ['ninpou', 'doton', 'fuuton', 'suiton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'flechas',
    name: 'Flechas',
    unlockLevel: 3,
    category: 'projectile',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: '2 por projétil; 1 projétil por nível usado',
    duration: 'Instantânea',
    target: 'Uma ou mais criaturas',
    chakraCost: 'Padrão do poder',
    description: 'Vários projéteis (flechas, agulhas, shurikens, bolas). Pode dividir entre alvos. Defesa única por alvo. Bônus de dano aplicado só 1x por alvo. Pode ser usada como Finta (2 chakra, Prestidigitação).',
    evolutions: 'Nv 6: Se mirar em 1 alvo e ele esquivar, refaz teste (metade dano). Nv 9: Dano integral ao refazer.',
    availableFor: ALL,
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'lanca',
    name: 'Lança',
    unlockLevel: 3,
    category: 'projectile',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: 'Comum do poder (divisível entre alvos)',
    duration: 'Instantânea',
    target: 'Uma ou mais criaturas',
    chakraCost: 'Padrão do poder',
    description: 'Espinho pontiagudo que surge a até 2m e se estica. Ignora 3 de dureza de barreiras/objetos e 1 de Dureza de Corpo. Pode criar múltiplas lanças dividindo o dano.',
    evolutions: 'Nv 6: Surge de baixo do inimigo, ignora coberturas e bonificações de caído, ignora até 2 de Dureza de Corpo. Nv 9: Alvo testa Prontidão; se falhar fica desprevenido. Ignora toda Dureza.',
    availableFor: ['ninpou', 'doton', 'suiton'],
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'ricochete',
    name: 'Ricochete',
    unlockLevel: 3,
    category: 'projectile',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: 'Comum do poder',
    duration: 'Instantânea',
    target: 'Uma ou mais criaturas (1 + 1 a cada 2 níveis)',
    chakraCost: 'Padrão do poder',
    description: 'Raio que salta de alvo em alvo (máx 10m entre eles). Atinge alvos na ordem escolhida. Quando alguém defende com sucesso, o ricochete para.',
    evolutions: 'Nv 9: +1 dano base por novo alvo atingido (até +5).',
    availableFor: ALL,
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'coluna',
    name: 'Coluna',
    unlockLevel: 4,
    category: 'area',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: '2 por nível usado do poder',
    duration: 'Instantânea',
    target: 'Criaturas na área (cilindro)',
    chakraCost: 'Padrão do poder',
    description: 'Explosão em formato cilindro vertical com diâmetro e altura comuns do poder.',
    evolutions: 'Nv 7: Divide em mini-colunas de 1m. Nv 10: Mini-colunas cercam; teste Prontidão ou defesa debilitada (-2).',
    availableFor: ALL,
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'energizar',
    name: 'Energizar',
    unlockLevel: 4,
    category: 'support',
    action: 'Parcial',
    range: 'Pessoal',
    baseDamage: 'Substitui Força/Destreza por Espírito no cálculo',
    duration: 'Sustentada',
    target: 'Arma ou compartimento de projéteis',
    chakraCost: '3',
    description: 'Energiza punho/arma/projéteis. Recebe vantagens/fraquezas do elemento (sem bônus dano/dureza). Permite Bloqueio contra projéteis. Pode usar junto com Criar Arma (mesmo elemento). Incompatível com outras técnicas de suporte corpo-a-corpo.',
    evolutions: 'Punho de Ferro Energizado: pode usar Espírito no lugar de Força para o dano de arma.',
    availableFor: ALL,
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'nuvem',
    name: 'Nuvem',
    unlockLevel: 4,
    category: 'area',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: '1 fixo por nível usado (por turno)',
    duration: 'Concentração',
    target: 'Criaturas na área (círculo, dobro do tamanho comum)',
    chakraCost: 'Padrão do poder',
    description: 'Nuvem corrosiva/quente disparada em cone, assenta-se em área circular. A cada turno, criaturas testam Vigor; falha = dano + lento. Usuário imune.',
    evolutions: 'Nv 7: Duração passa a Sustentada. Nv 10: +3 dureza e dano fixo dobrado.',
    availableFor: ['ninpou', 'doton', 'fuuton', 'suiton'],
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'sopro-destrutivo',
    name: 'Sopro Destrutivo',
    unlockLevel: 4,
    category: 'area',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: 'Comum do poder',
    duration: 'Instantânea',
    target: 'Criaturas na área (cone)',
    chakraCost: 'Padrão do poder',
    description: 'Sopro que se espalha para frente e lados em cone. Dano a todos na área.',
    evolutions: 'Nv 7: Alvo que Esquivou/Antecipou testa Acrobacia; falha = dano grau 1 remanescente. Nv 10: Dano remanescente grau 2.',
    availableFor: ALL,
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'correnteza',
    name: 'Correnteza',
    unlockLevel: 5,
    category: 'area',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: 'Comum do poder',
    duration: 'Instantânea',
    target: 'Criaturas na área (onda)',
    chakraCost: 'Padrão do poder',
    description: 'Correnteza de fluido varrendo oponentes. Teste Vigor (dif padrão -2) ou empurrado. Colisão contra obstáculo = +1 dano de concussão.',
    evolutions: 'Nv 8: Falha no Vigor + colisão = atordoado até próximo turno. Pode moldar a largura da onda.',
    availableFor: ['ninpou', 'doton', 'fuuton', 'suiton'],
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'missil',
    name: 'Míssil',
    unlockLevel: 5,
    category: 'area',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: 'Comum do poder + bônus',
    duration: 'Instantânea',
    target: 'Criaturas na área (linha)',
    chakraCost: 'Padrão do poder',
    description: 'Múltiplos projéteis em sequência (linha). Após acertar, role ataque novamente; acertou = +1 dano base. Dragão de Fogo (Katon): contra alvo amarrado por kousen, ação parcial.',
    evolutions: 'Nv 8: Dois re-rolls após acerto. Nv 10: Quatro re-rolls.',
    availableFor: ALL,
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'onda-explosiva',
    name: 'Onda Explosiva',
    unlockLevel: 5,
    category: 'area',
    action: 'Padrão',
    range: 'Pessoal (ao redor)',
    baseDamage: 'Comum do poder',
    duration: 'Instantânea',
    target: 'Criaturas na área (meia-esfera ou círculo)',
    chakraCost: 'Padrão do poder',
    description: 'Onda de choque ao redor, centrada em si. Atingidos testam Vigor (dif padrão -2) ou são empurrados. Não permite Potencializar.',
    evolutions: 'Nv 8: Falha no Vigor também deixa a vítima caída.',
    availableFor: ALL,
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'algemar',
    name: 'Algemar',
    unlockLevel: 6,
    category: 'projectile',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: '',
    duration: 'Concentração',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Prende pernas do inimigo; alvo fica impedido. Pode destruir algemas (dureza comum) ou testar Força/Escapar (ação padrão). Ataques em área também danificam as algemas.',
    evolutions: 'Nv 8: Duração Sustentada. Nv 10: Até 3 alvos (5m entre si); usar 2x nos mesmos = indefesos.',
    availableFor: ['ninpou', 'doton', 'suiton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Ninpou',
  },

  // ── Ninpou Gerais (Guia Avançado) ─────────────────────────────────────────
  {
    _id: 'dano-continuo',
    name: 'Dano Contínuo',
    unlockLevel: 2,
    category: 'projectile',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: 'Dano fixo igual ao nível do poder',
    duration: 'Instantânea (efeito contínuo até 3 turnos)',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Projétil que cria ferimentos contínuos (fogo, carga elétrica, etc.). Vítima sofre dano fixo igual ao nível do poder a cada turno. Pode remover com ação completa + teste de Vigor (dif comum -3) ou 3 turnos.',
    evolutions: 'Nv 7: Duração máxima 5 turnos, dificuldade do teste = dif comum do poder, só se extingue com condições especiais.',
    availableFor: ['katon', 'raiton'],
    dealsDamage: true,
    source: 'avancado',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'deslocamento-de-vacuo',
    name: 'Deslocamento de Vácuo',
    unlockLevel: 2,
    category: 'support',
    action: 'Parcial',
    range: 'Comum do poder',
    baseDamage: '',
    duration: '1 rodada',
    target: 'Uma criatura',
    chakraCost: '2',
    description: 'Manipula o elemento para diminuir resistência atmosférica, facilitando deslocamento do alvo. O alvo ganha bônus no deslocamento igual a ½ Espírito até o próximo turno.',
    evolutions: 'Nv 7: Até 5 alvos; custo de chakra = 3 (pago uma vez).',
    availableFor: ['doton', 'fuuton', 'suiton'],
    dealsDamage: false,
    source: 'avancado',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'projetar',
    name: 'Projetar',
    unlockLevel: 2,
    category: 'projectile',
    action: 'Padrão',
    range: '½ Comum do poder',
    baseDamage: 'Comum do poder -1',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Projétil que desloca o oponente. Teste Vigor (dif comum -2) ou deslocado em metros igual ao grau de dano causado. Inimigos deslocados não são derrubados.',
    evolutions: 'Nv 7: Não pode ser bloqueada, dano = Comum do poder, deslocamento = ½ Tamanho Comum, falha crítica no Vigor = Caído.',
    availableFor: ['ninpou', 'doton', 'fuuton', 'suiton'],
    dealsDamage: true,
    source: 'avancado',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'purificar',
    name: 'Purificar',
    unlockLevel: 2,
    category: 'support',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: '',
    duration: 'Instantânea',
    target: 'Ambiente (área circular)',
    chakraCost: 'Padrão do poder',
    description: 'Purifica uma área de veneno, impureza ou substância perigosa. Para efeitos derivados de poder, o nível usado deve ser maior que o do efeito no ambiente.',
    evolutions: '',
    availableFor: ['fuuton', 'suiton'],
    dealsDamage: false,
    source: 'avancado',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'repelir',
    name: 'Repelir',
    unlockLevel: 2,
    category: 'support',
    action: 'Movimento',
    range: 'Comum do poder',
    baseDamage: '',
    duration: 'Instantânea',
    target: 'Defesa reativa',
    chakraCost: 'Padrão do poder',
    description: 'Usado reativamente contra projétil, técnica de toque ou golpear. Teste de LM +1 precisão para criar proteção de Dureza Comum do Poder. Se absorve completamente, repele adjacentes 1m.',
    evolutions: 'Nv 7: Usos subsequentes = ação livre e metade do chakra. Sem teste de concentração com adversário adjacente.',
    availableFor: ['ninpou', 'doton', 'fuuton', 'suiton'],
    dealsDamage: false,
    source: 'avancado',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'cegante',
    name: 'Cegante',
    unlockLevel: 5,
    category: 'projectile',
    action: 'Padrão',
    range: '½ Comum do poder',
    baseDamage: 'Comum do poder',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Projétil mirando o rosto do alvo. Se acertar, a vítima sofre penalidades de camuflagem parcial até limpar o rosto (ação padrão sem teste, ou ação de movimento + teste) ou 3 turnos.',
    evolutions: 'Nv 8: Penalidades passam a camuflagem total; tempo para limpeza natural = 5 turnos.',
    availableFor: ['ninpou', 'doton', 'fuuton', 'suiton'],
    dealsDamage: true,
    source: 'avancado',
    sourceDetail: 'Ninpou',
  },
  {
    _id: 'desastre',
    name: 'Desastre',
    unlockLevel: 9,
    category: 'area',
    action: 'Concentração',
    range: 'Epicentro até 2x distância comum do poder',
    baseDamage: '3x Nível do poder',
    duration: 'Concentração',
    target: 'Criaturas e estruturas na área (3x tamanho comum)',
    chakraCost: '3x Nível do poder',
    description: 'Canaliza chakra para causar desastre natural (tempestade, furacões, terremotos, maremotos). Todos na área ficam Lentos; sofrem ataque de CD a cada turno. Pode proteger aliados (ação livre + teste de Concentração). 1x por cena, sem aptidões de técnica.',
    evolutions: '',
    availableFor: ['ninpou', 'doton', 'fuuton', 'raiton', 'suiton'],
    dealsDamage: true,
    source: 'avancado',
    sourceDetail: 'Ninpou',
  },

  // ── Efeitos Exclusivos de Elemento (Livro Básico) ─────────────────────────
  {
    _id: 'imergir',
    name: 'Imergir',
    unlockLevel: 2,
    category: 'support',
    action: 'Completa',
    range: 'Pessoal',
    baseDamage: '',
    duration: 'Contínua',
    target: 'O próprio usuário',
    chakraCost: 'Padrão do poder',
    description: 'Funde-se com o elemento (chão, parede). Recebe Perito: Furtividade. Visão limitada a 10m. Falsa Decapitação: se oculto, pode Agarrar alvo acima como ataque furtivo.',
    evolutions: 'Nv 4: Pode se mover (½ deslocamento) e sentidos normais.',
    availableFor: ['doton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Doton',
  },
  {
    _id: 'tremor',
    name: 'Tremor',
    unlockLevel: 2,
    category: 'area',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: '',
    duration: 'Instantânea',
    target: 'Criaturas na área (círculo 2m)',
    chakraCost: 'Padrão do poder',
    description: 'Chão treme na área. Falha na defesa = caído. Opcionalmente, pode gastar ação de movimento para Acrobacia e se manter de pé.',
    evolutions: 'Nv 4: Círculo com diâmetro comum do poder (maior área).',
    availableFor: ['doton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Doton',
  },
  {
    _id: 'nevoa',
    name: 'Névoa',
    unlockLevel: 2,
    category: 'support',
    action: 'Padrão',
    range: '1m',
    baseDamage: '',
    duration: 'Sustentada',
    target: 'Ambiente (círculo 30m + 3m por Espírito)',
    chakraCost: 'Padrão do poder',
    description: 'Nevoeiro. Só enxerga perfeitamente até 1m. Além = camuflagem parcial (25% falha). Requer Lutar às Cegas ou habilidade de sensor.',
    evolutions: 'Nv 5: Até 1m = camuflagem parcial; além = camuflagem total (50% falha, sem visão).',
    availableFor: ['suiton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Suiton',
  },
  {
    _id: 'lamina-de-raios',
    name: 'Lâmina de Raios',
    unlockLevel: 2,
    category: 'touch',
    action: 'Movimento (preparar) + Padrão (atacar)',
    range: 'Toque',
    baseDamage: 'Comum do poder, ignora 1 dureza',
    duration: 'Sustentada (1 ataque)',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Concentra eletricidade na mão (som de pássaros). Destrói arma usada em Bloqueio. Ataque surpresa em alvo desprevenido = mín. grau 2. Requer Espírito 8.',
    evolutions: 'Nv 5: Preparar = ação parcial; pode usar Investida (+2 dano, +1/nível). Nv 7: Ignora qualquer dureza. Nv 9: Crítico Aprimorado.',
    availableFor: ['raiton'],
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Raiton',
  },
  {
    _id: 'prisao-de-agua',
    name: 'Prisão de Água',
    unlockLevel: 3,
    category: 'projectile',
    action: 'Padrão',
    range: '1m',
    baseDamage: '',
    duration: 'Concentração',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Redoma de água aprisiona alvo = paralisado. Teste CD a 1m (-3 precisão). Necessário contato. Vítima pode testar Força ou Vigor para se libertar. Pode usar via Mizu Bunshin.',
    evolutions: 'Nv 9: Prisão sufocante (preenchida com água, teste sufocamento). Via Mizu Bunshin = duração sustentada.',
    availableFor: ['suiton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Suiton',
  },
  {
    _id: 'arma-eletrica',
    name: 'Arma Elétrica',
    unlockLevel: 4,
    category: 'support',
    action: 'Parcial',
    range: 'Pessoal',
    baseDamage: 'Variável (ver texto)',
    duration: 'Sustentada',
    target: 'O próprio usuário',
    chakraCost: '1 a 4 (depende do tipo)',
    description: 'Funciona como Criar Arma + Energizar. Energizar (3 chakra): só armas de corte/perfuração. Criar Projéteis (1 chakra): armas simples elétricas. Criar Lâmina (4 chakra): espada curta, ignora 1 dureza, pode estender até 5m. Requer Lâmina de Raios.',
    evolutions: 'Nv 8: Destrói arma comum bloqueada (exceto Energizar Doton).',
    availableFor: ['raiton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Raiton',
  },
  {
    _id: 'inflamavel',
    name: 'Inflamável',
    unlockLevel: 5,
    category: 'support',
    action: 'Movimento',
    range: 'Comum do poder',
    baseDamage: 'Bônus (+2 ao combustor)',
    duration: 'Instantânea',
    target: 'Ambiente (área circular)',
    chakraCost: '3 + chakra do efeito de combustão',
    description: 'Cria líquido/gás inflamável. Não causa dano sozinho. Com ação padrão, usa Canhão (Katon/Raiton) para detonar: explosão com área deste efeito, dano do Canhão +2.',
    evolutions: 'Nv 8: Pode usar qualquer efeito Katon/Raiton instantâneo para combustão. Modo Contínuo: qualquer faísca causa ignição.',
    availableFor: ['fuuton', 'katon', 'suiton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Katon',
  },
  {
    _id: 'venenoso',
    name: 'Venenoso',
    unlockLevel: 5,
    category: 'area',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: '',
    duration: 'Instantânea',
    target: 'Criaturas na área (cone)',
    chakraCost: 'Padrão do poder',
    description: 'Cria névoa/fumaça venenosa usando veneno produzido com Venefício (até nível II). Garante injeção do veneno; alvo testa resistência. Veneno consumido.',
    evolutions: '',
    availableFor: ['fuuton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Fuuton',
  },
  {
    _id: 'flutuar',
    name: 'Flutuar',
    unlockLevel: 5,
    category: 'support',
    action: 'Movimento',
    range: 'Pessoal',
    baseDamage: '',
    duration: 'Sustentada',
    target: 'O próprio usuário',
    chakraCost: '5',
    description: 'Requer Leque Gigante empunhado. Usando Kinobori, ganha perícia Voo com precisão = nível de Espírito e condição Alado. Pode ser usado como reação a uma queda. Leque fica inutilizável enquanto sustentado.',
    evolutions: '',
    availableFor: ['fuuton'],
    dealsDamage: false,
    source: 'avancado',
    sourceDetail: 'Fuuton',
  },
  {
    _id: 'afiar',
    name: 'Afiar',
    unlockLevel: 6,
    category: 'support',
    action: 'Parcial',
    range: 'Pessoal',
    baseDamage: '',
    duration: 'Sustentada',
    target: 'Uma arma cortante ou perfurante real',
    chakraCost: '3',
    description: 'Inclui benefícios de Energizar + extras. Fio melhorado: ignora 1 dureza. Destrói arma comum bloqueada. Crítico Melhorado: margem +1. Lâmina Estendida: +30cm na arma. Requer Energizar.',
    evolutions: '',
    availableFor: ['fuuton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Fuuton',
  },
  {
    _id: 'descarga',
    name: 'Descarga',
    unlockLevel: 6,
    category: 'area',
    action: 'Padrão',
    range: 'Comum do poder ou Toque',
    baseDamage: 'Metade do dano comum',
    duration: 'Instantânea',
    target: 'Criaturas na área (meia-esfera ou círculo)',
    chakraCost: 'Padrão do poder',
    description: 'Corrente elétrica ao redor. Se causar dano: teste Vigor (dif padrão -3), falha = atordoado. Pode concentrar em projétil único ou descarregar via Energizar Raiton.',
    evolutions: '',
    availableFor: ['raiton'],
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Raiton',
  },
  {
    _id: 'pele-de-pedra',
    name: 'Pele de Pedra',
    unlockLevel: 6,
    category: 'support',
    action: 'Movimento',
    range: 'Pessoal',
    baseDamage: '',
    duration: 'Instantânea (até fim do turno) ou Sustentada (1 dureza)',
    target: 'O próprio usuário',
    chakraCost: 'Padrão do poder',
    description: 'Concede dureza de corpo = dureza padrão + 2. Pode sustentar (1 de dureza sem bônus elemento). Soco de Pedra: Energizar Doton junto = socos dano letal 4.',
    evolutions: 'Nv 9: Dureza sustentada = 2. Bloqueio ineficaz contra Soco de Pedra.',
    availableFor: ['doton'],
    dealsDamage: false,
    source: 'basico',
    sourceDetail: 'Doton',
  },
  {
    _id: 'colisao-de-ondas',
    name: 'Colisão de Ondas',
    unlockLevel: 6,
    category: 'area',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: '10 fixo, dobrado vs construções',
    duration: 'Concentração',
    target: 'Criaturas na área (onda)',
    chakraCost: 'Padrão do poder',
    description: 'Massa d\'água avança violentamente. Pode manter por concentração (½ chakra/turno). Falha na defesa = capturado pelas ondas; deve testar Atletismo (nadar) ou sofre sufocamento.',
    evolutions: 'Nv 8: Dano base 14. Nv 10: Dano base 18; vítima não pode usar ação padrão para nadar sem testes.',
    availableFor: ['suiton'],
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Suiton',
  },
  {
    _id: 'lamina-de-vento',
    name: 'Lâmina de Vento',
    unlockLevel: 7,
    category: 'projectile',
    action: 'Completa',
    range: '5m',
    baseDamage: '1 por nível usado + bônus Fuuton (+2)',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Lâminas invisíveis giratórias, 1 por nível usado. Teste único de acerto e defesa. Alvo testa Prontidão para enxergar; falha = fintado. Requer Energizar.',
    evolutions: 'Nv 10: Falha no Prontidão = desprevenido.',
    availableFor: ['fuuton'],
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Fuuton',
  },
  {
    _id: 'meteoros',
    name: 'Meteoros',
    unlockLevel: 9,
    category: 'area',
    action: 'Completa',
    range: 'Comum do poder',
    baseDamage: '1 fixo por nível usado, por meteoro',
    duration: 'Instantânea',
    target: 'Criaturas na área (seis esferas de 5m)',
    chakraCost: 'Padrão do poder',
    description: 'Seis meteoros voam até ponto escolhido e explodem. Dano fixo por nível (sem bônus). Múltiplos meteoros acumulam. Pode mirar em criaturas específicas (-3 precisão).',
    evolutions: '',
    availableFor: ['katon'],
    dealsDamage: true,
    source: 'basico',
    sourceDetail: 'Katon',
  },

  // ── Hijutsus: Nintaijutsu ─────────────────────────────────────────────────
  {
    _id: 'forca-bruta',
    name: 'Força Bruta',
    unlockLevel: 1,
    category: 'melee',
    action: 'Padrão',
    range: 'Toque (CC)',
    baseDamage: 'Nível do poder + ½ Força',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: '0',
    description: 'Recebe Punho de Ferro. Pode usar aptidões de manobra e bônus de dano.',
    evolutions: '',
    availableFor: ['nintaijutsu'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Nintaijutsu',
  },
  {
    _id: 'elbow',
    name: 'Elbow',
    unlockLevel: 2,
    category: 'melee',
    action: 'Padrão',
    range: 'Toque (CC)',
    baseDamage: 'Nível do poder + ½ Força',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Cotovelada + teste Vigor ou arremessado 5m + 1m por Força.',
    evolutions: 'Nv 5: Metade da distância mesmo com sucesso no Vigor.',
    availableFor: ['nintaijutsu'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Nintaijutsu',
  },
  {
    _id: 'straight',
    name: 'Straight',
    unlockLevel: 3,
    category: 'melee',
    action: 'Completa',
    range: 'Toque (CC)',
    baseDamage: 'Nível do poder + ½ Força',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Avanço rápido (mín 10m). Teste Vigor ou arremessado 10m + 2m por Força, caído.',
    evolutions: 'Nv 6: +2 Agilidade na finta.',
    availableFor: ['nintaijutsu'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Nintaijutsu',
  },
  {
    _id: 'lariat',
    name: 'Lariat',
    unlockLevel: 4,
    category: 'melee',
    action: 'Completa',
    range: 'Toque (CC)',
    baseDamage: 'Comum do poder +1',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Avanço rápido, dano comum +1. Deve continuar correndo 5m+.',
    evolutions: 'Nv 8: +1 dano por 5m percorridos (máx +3).',
    availableFor: ['nintaijutsu'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Nintaijutsu',
  },
  {
    _id: 'hell-stab',
    name: 'Hell Stab',
    unlockLevel: 5,
    category: 'touch',
    action: 'Movimento + Padrão',
    range: 'Toque',
    baseDamage: 'Comum do poder',
    duration: 'Sustentada (1 ataque)',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Igual Lâmina de Raios Nv 5, mas usa Força em vez de Espírito.',
    evolutions: 'Nv 7: = Lâmina Nv 7. Nv 9: = Lâmina Nv 9 + Domínio do Raio grátis.',
    availableFor: ['nintaijutsu'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Nintaijutsu',
  },
  {
    _id: 'guillotine-drop',
    name: 'Guillotine Drop',
    unlockLevel: 7,
    category: 'melee',
    action: 'Padrão',
    range: 'Toque (CC)',
    baseDamage: 'Nível do poder + ½ Força',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Chute de cima para baixo. Teste Vigor ou atordoado + caído 1 turno.',
    evolutions: '',
    availableFor: ['nintaijutsu'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Nintaijutsu',
  },
  {
    _id: 'linger-bomb',
    name: 'Linger Bomb',
    unlockLevel: 9,
    category: 'melee',
    action: 'Padrão',
    range: 'Toque (CC)',
    baseDamage: 'Força integral (sem divisão)',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Agarrar + arremessar no chão. Dano com Força integral. Sem bônus de dano.',
    evolutions: '',
    availableFor: ['nintaijutsu'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Nintaijutsu',
  },
  {
    _id: 'reverse-chop',
    name: 'Reverse Chop',
    unlockLevel: 10,
    category: 'melee',
    action: 'Padrão',
    range: 'Toque (CC)',
    baseDamage: 'Nível do poder + ½ Força',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Como Guillotine Drop, mas nunca menos que Grau 3 de dano.',
    evolutions: '',
    availableFor: ['nintaijutsu'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Nintaijutsu',
  },

  // ── Hijutsus: Kamijutsu ───────────────────────────────────────────────────
  {
    _id: 'anjo-de-paper',
    name: 'Anjo de Paper',
    unlockLevel: 5,
    category: 'support',
    action: 'Ver texto',
    range: 'Pessoal',
    baseDamage: '',
    duration: 'Sustentada',
    target: 'O próprio usuário',
    chakraCost: 'Ver texto',
    description: 'Asas de papel. Voo = Espírito/Arte. Voo Rápido. Pode usar Flechas Nv 3. Requer Shikigami no Mai.',
    evolutions: '',
    availableFor: ['kamijutsu'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Kamijutsu',
  },
  {
    _id: 'julgamento',
    name: 'Julgamento',
    unlockLevel: 6,
    category: 'touch',
    action: 'Completa',
    range: 'Comum do poder',
    baseDamage: 'Sufocamento (= dano base)',
    duration: 'Concentração',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Envolve alvo com papéis. Indefeso + sufocamento. Requer Anjo de Paper e Shikigami no Mai Nv 2.',
    evolutions: 'Nv 9: Múltiplos alvos ou alvo não-capanga.',
    availableFor: ['kamijutsu'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Kamijutsu',
  },
  {
    _id: 'emissario-divino',
    name: 'Emissário Divino',
    unlockLevel: 10,
    category: 'area',
    action: 'Ver texto',
    range: 'Comum do poder',
    baseDamage: '2x nível',
    duration: 'Instantânea',
    target: 'Criaturas na área',
    chakraCost: '10 + 12 PK',
    description: 'Transforma ambiente em bilhões de papéis com selos explosivos. 3 estágios. Explosão: alvos indefesos, Golpe de Misericórdia. Ignora dureza. Usuário sofre Grau 3. Requer Fuuinjutsu 8.',
    evolutions: '',
    availableFor: ['kamijutsu'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Kamijutsu',
  },

  // ── Hijutsus: Senninka ────────────────────────────────────────────────────
  {
    _id: 'corrente',
    name: 'Corrente',
    unlockLevel: 3,
    category: 'melee',
    action: 'Parcial',
    range: 'Pessoal (10m)',
    baseDamage: '',
    duration: 'Contínua',
    target: 'O próprio usuário',
    chakraCost: 'Padrão do poder',
    description: 'Estica braço até 10m. Agarrar à distância sem penalidade.',
    evolutions: '',
    availableFor: ['senninka'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Senninka',
  },
  {
    _id: 'transferencia-celular',
    name: 'Transferência Celular',
    unlockLevel: 6,
    category: 'touch',
    action: '1 rodada',
    range: 'Toque',
    baseDamage: '',
    duration: 'Instantânea',
    target: 'Uma criatura (fora de combate)',
    chakraCost: 'Padrão do poder',
    description: 'Absorve Vitalidade de alvo fora de combate (mata). Ou doa até 15 Vitalidade (rejuvenesce).',
    evolutions: '',
    availableFor: ['senninka'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Senninka',
  },

  // ── Hijutsus: Ichibi (Shukaku) ────────────────────────────────────────────
  {
    _id: 'areia-especial',
    name: 'Areia Especial',
    unlockLevel: 2,
    category: 'support',
    action: 'Reação',
    range: 'Pessoal',
    baseDamage: '',
    duration: 'Contínua',
    target: 'O próprio usuário',
    chakraCost: '0',
    description: 'Areia alimentada com chakra. Defesa Rápida (bloqueia sem custo). Barreira Rápida como reação.',
    evolutions: 'Nv 8: Funciona contra finta e Amaterasu.',
    availableFor: ['ichibi'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Ichibi (Shukaku)',
  },
  {
    _id: 'armadura-de-areia',
    name: 'Armadura de Areia',
    unlockLevel: 3,
    category: 'support',
    action: 'Padrão',
    range: 'Pessoal',
    baseDamage: '',
    duration: 'Contínua',
    target: 'O próprio usuário',
    chakraCost: 'Padrão do poder',
    description: 'Dureza corpo 1 por nível par (máx 3). Quebra com acerto crítico. -5m deslocamento, -3 Esquiva/Agilidade.',
    evolutions: '',
    availableFor: ['ichibi'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Ichibi (Shukaku)',
  },
  {
    _id: 'terceiro-olho',
    name: 'Terceiro Olho',
    unlockLevel: 3,
    category: 'support',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: '',
    duration: 'Concentração',
    target: 'Ambiente',
    chakraCost: 'Padrão do poder',
    description: 'Olho artificial flutuante de areia para espionagem. Pode ser escondido.',
    evolutions: '',
    availableFor: ['ichibi'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Ichibi (Shukaku)',
  },
  {
    _id: 'prisao-de-areia',
    name: 'Prisão de Areia',
    unlockLevel: 5,
    category: 'projectile',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: 'Funeral: metade do dano',
    duration: 'Concentração',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Imobiliza alvo à distância. Funeral de Areia: golpe de misericórdia.',
    evolutions: 'Nv 9: Sufocante, Funeral causa dano completo.',
    availableFor: ['ichibi'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Ichibi (Shukaku)',
  },
  {
    _id: 'areia-suspensa',
    name: 'Areia Suspensa',
    unlockLevel: 5,
    category: 'support',
    action: 'Ver texto',
    range: 'Pessoal',
    baseDamage: '',
    duration: 'Sustentada',
    target: 'O próprio usuário',
    chakraCost: '2',
    description: 'Atacar de cima (finta com Destreza). Nuvem de transporte (Voo = Espírito). Barreira suspensa.',
    evolutions: '',
    availableFor: ['ichibi'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Ichibi (Shukaku)',
  },
  {
    _id: 'piramide',
    name: 'Pirâmide',
    unlockLevel: 9,
    category: 'support',
    action: 'Completa',
    range: 'Comum do poder',
    baseDamage: '',
    duration: 'Contínua',
    target: 'Uma criatura presa',
    chakraCost: 'Padrão do poder',
    description: 'Reforça Prisão de Areia. Dureza 3x nível. Sufocante. Com Fuuinjutsu 8: impede quebra por dentro.',
    evolutions: '',
    availableFor: ['ichibi'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Ichibi (Shukaku)',
  },

  // ── Hijutsus: Hozuki ──────────────────────────────────────────────────────
  {
    _id: 'braco-de-agua',
    name: 'Braço de Água',
    unlockLevel: 5,
    category: 'melee',
    action: 'Parcial',
    range: 'Pessoal',
    baseDamage: 'Ver texto',
    duration: 'Contínua',
    target: 'O próprio usuário',
    chakraCost: '1',
    description: 'Aumenta um braço. Usa Espírito no lugar de Força para testes e dano corpo-a-corpo. Permite Acuidade com armas pesadas.',
    evolutions: '',
    availableFor: ['hozuki'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Hozuki',
  },
  {
    _id: 'afogar',
    name: 'Afogar',
    unlockLevel: 6,
    category: 'touch',
    action: 'Movimento',
    range: 'Toque',
    baseDamage: 'Sufocamento (= dano base comum)',
    duration: 'Contínua',
    target: 'Uma criatura agarrada',
    chakraCost: 'Padrão do poder',
    description: 'Envolve cabeça do alvo em bolha d\'água. Dano fixo = dano base comum. Bolha tem absorção 1, dureza comum do poder.',
    evolutions: '',
    availableFor: ['hozuki'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Hozuki',
  },
  {
    _id: 'monstro-de-agua',
    name: 'Monstro de Água',
    unlockLevel: 7,
    category: 'support',
    action: 'Padrão',
    range: 'Pessoal',
    baseDamage: 'Braço de Água +3 Espírito',
    duration: 'Sustentada',
    target: 'O próprio usuário',
    chakraCost: 'Padrão do poder',
    description: 'Funde-se com água para virar monstro Enorme. Ataques corporais com Braço de Água +3 Espírito.',
    evolutions: '',
    availableFor: ['hozuki'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Hozuki',
  },
  {
    _id: 'clone-de-oleo',
    name: 'Clone de Óleo',
    unlockLevel: 8,
    category: 'area',
    action: 'Padrão',
    range: 'Pessoal',
    baseDamage: 'Comum +2 (explosão)',
    duration: 'Concentração',
    target: 'Criaturas na área (esfera)',
    chakraCost: 'Padrão do poder',
    description: 'Clone chibi de água + óleo. Cresce +1 tamanho por turno. Ao atingir Imenso, explode (dano comum +2). Reinicia ciclo. Acelerado, dano de arma +5.',
    evolutions: '',
    availableFor: ['hozuki'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Hozuki',
  },

  // ── Hijutsus: Yuki ────────────────────────────────────────────────────────
  {
    _id: 'espelhos-demoniacos',
    name: 'Espelhos Demoníacos',
    unlockLevel: 6,
    category: 'area',
    action: 'Padrão',
    range: 'Pessoal',
    baseDamage: '',
    duration: 'Contínua',
    target: 'Criaturas na área (meia-esfera, 1m/nível)',
    chakraCost: '3/turno',
    description: '21 espelhos de gelo formando cúpula. Absorção = 8x nível. Usuário pode entrar nos espelhos (indetectável). Finta acelerada para ataques.',
    evolutions: 'Nv 8: Dureza 2, pode usar Flechas.',
    availableFor: ['yuki'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Yuki',
  },

  // ── Hijutsus: Hoshigaki ───────────────────────────────────────────────────
  {
    _id: 'prisao-do-tubarao',
    name: 'Prisão do Tubarão',
    unlockLevel: 10,
    category: 'area',
    action: 'Completa',
    range: 'Pessoal',
    baseDamage: '',
    duration: 'Sustentada',
    target: 'Criaturas na área (esfera, dobro do tamanho comum)',
    chakraCost: 'Padrão do poder',
    description: 'Redoma gigante de água que captura todos na área. Absorção = 6x nível. Vítimas testam Atletismo (nadar) ou Vigor (prender respiração). Usuário pode mover a redoma.',
    evolutions: '',
    availableFor: ['hoshigaki'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Hoshigaki',
  },

  // ── Hijutsus: Jiton ───────────────────────────────────────────────────────
  {
    _id: 'areia-selada',
    name: 'Areia Selada',
    unlockLevel: 3,
    category: 'support',
    action: '1 rodada (selar)',
    range: 'Toque',
    baseDamage: '',
    duration: 'Permanente',
    target: 'O próprio usuário',
    chakraCost: 'Ver texto',
    description: 'Selo de Fuuinjutsu para armazenar Areia de Ferro/Pó de Ouro na pele. Liberar = ação livre.',
    evolutions: '',
    availableFor: ['jiton'],
    dealsDamage: false,
    source: 'hijutsus',
    sourceDetail: 'Jiton',
  },
  {
    _id: 'projetil-venenoso',
    name: 'Projétil Venenoso',
    unlockLevel: 5,
    category: 'projectile',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: 'Regras de Flechas Nv 3',
    duration: 'Instantânea',
    target: 'Uma ou mais criaturas',
    chakraCost: 'Padrão do poder',
    description: 'Areia de ferro moldada em projéteis com veneno. Regras de Flechas Nv 3. Precisa Grau 3+ para injetar veneno.',
    evolutions: '',
    availableFor: ['jiton'],
    dealsDamage: true,
    source: 'hijutsus',
    sourceDetail: 'Jiton',
  },

  // ── Hijutsus: Rokubi ──────────────────────────────────────────────────────
  {
    _id: 'bolha-de-tinta',
    name: 'Bolha de Tinta',
    unlockLevel: 2,
    category: 'projectile',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: 'Comum do poder',
    duration: 'Instantânea',
    target: 'Uma criatura',
    chakraCost: 'Padrão do poder',
    description: 'Sopra bolhas que cercam o rosto e ao estourar criam nuvem de pó vermelho, cegando o alvo por 1 turno. Sucesso automático na segunda vez contra o mesmo alvo na mesma cena.',
    evolutions: 'Nv 5: Múltiplos alvos (1 por cada 2 níveis no poder), a no máximo 4m entre si.',
    availableFor: ['rokubi'],
    dealsDamage: true,
    source: 'avancado',
    sourceDetail: 'Rokubi',
  },
  {
    _id: 'sopro-acido',
    name: 'Sopro Ácido',
    unlockLevel: 4,
    category: 'area',
    action: 'Padrão',
    range: 'Comum do poder',
    baseDamage: 'Comum do poder',
    duration: 'Instantânea',
    target: 'Criaturas na área (cone)',
    chakraCost: 'Padrão do poder',
    description: 'Sopra bolhas que explodem ao contato e deixam líquido corrosivo. Funciona como Sopro Destrutivo de Ninpou, com as mesmas evoluções.',
    evolutions: 'Mesmas evoluções de Sopro Destrutivo.',
    availableFor: ['rokubi'],
    dealsDamage: true,
    source: 'avancado',
    sourceDetail: 'Rokubi',
  },
  {
    _id: 'bolha-sufocante',
    name: 'Bolha Sufocante',
    unlockLevel: 5,
    category: 'area',
    action: 'Padrão',
    range: 'Toque',
    baseDamage: 'Sufocamento (= dano comum do poder)',
    duration: 'Contínua',
    target: 'Criaturas na área (círculo)',
    chakraCost: 'Padrão do poder',
    description: 'Sopra bolhas que quando atingem a cabeça, envolvem e sufocam o alvo. Para se libertar, causar qualquer dano à bolha (dureza comum do poder).',
    evolutions: '',
    availableFor: ['rokubi'],
    dealsDamage: true,
    source: 'avancado',
    sourceDetail: 'Rokubi',
  },
  {
    _id: 'bolha-flutuante',
    name: 'Bolha Flutuante',
    unlockLevel: 7,
    category: 'support',
    action: 'Completa',
    range: 'Pessoal',
    baseDamage: '',
    duration: 'Concentração',
    target: 'O próprio usuário (até 2 pessoas)',
    chakraCost: '3',
    description: 'Cria bolha resistente para transporte aéreo (até 2 pessoas). Ganha Voo = Espírito do usuário. Deslocamento = 10m + 1m por nível do poder. Dureza = dobro da padrão. Atacar de dentro destrói a bolha. Requer Barreira Nv 6.',
    evolutions: '',
    availableFor: ['rokubi'],
    dealsDamage: false,
    source: 'avancado',
    sourceDetail: 'Rokubi',
  },
].map((t) => ({ ...t, system: 'naruto', active: true }));

async function run() {
  let upserts = 0;
  for (const tpl of TEMPLATES) {
    await NarutoTechTemplate.findByIdAndUpdate(
      tpl._id,
      { $setOnInsert: tpl },
      { upsert: true, returnDocument: 'before' },
    );
    upserts++;
  }
  console.log(`[migrateNarutoTechTemplates] Ensured ${upserts} technique templates.`);
}

module.exports = { run };
